version: '2'

services:
        client:
                build: ./client
                ports:
                        - 8082:8082
                environment:
                        - SERVER_URL=http://backend:9000
        backend:
                build: ./backend
                ports:
                        - 9000:9000

