apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T08:09:31Z"
  labels:
    app: adder
  name: adder
  namespace: default
  resourceVersion: "2569"
  selfLink: /api/v1/namespaces/default/services/adder
  uid: b6120555-8131-4d94-b6fc-470ab261962f
spec:
  clusterIP: 10.109.182.250
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30967
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: adder
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.202
