apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T08:09:17Z"
  labels:
    app: front
  name: front
  namespace: default
  resourceVersion: "2523"
  selfLink: /api/v1/namespaces/default/services/front
  uid: 1f4e726b-f976-4aab-b956-0d5acb75d829
spec:
  clusterIP: 10.99.198.66
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32341
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: front
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.200
