apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T08:09:23Z"
  labels:
    app: source
  name: source
  namespace: default
  resourceVersion: "2546"
  selfLink: /api/v1/namespaces/default/services/source
  uid: 45da36ed-693c-4536-82ec-738242313f3d
spec:
  clusterIP: 10.109.242.23
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32760
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: source
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.201
