apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-06-21T08:09:37Z"
  labels:
    app: suber
  name: suber
  namespace: default
  resourceVersion: "2582"
  selfLink: /api/v1/namespaces/default/services/suber
  uid: be024629-385e-4686-a93a-358e3a6ccac8
spec:
  clusterIP: 10.99.108.147
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30736
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: suber
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 172.17.0.203
