apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-06-21T08:08:47Z"
  generation: 1
  labels:
    app: suber
  name: suber
  namespace: default
  resourceVersion: "2561"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/suber
  uid: 83f6fd46-ed8e-46d0-a0b6-6a8a5e975cfc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: suber
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: suber
    spec:
      containers:
      - image: chanwit/suber
        imagePullPolicy: Always
        name: suber
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-06-21T08:09:30Z"
    lastUpdateTime: "2020-06-21T08:09:30Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-06-21T08:08:47Z"
    lastUpdateTime: "2020-06-21T08:09:30Z"
    message: ReplicaSet "suber-8577c5cdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
